// src/ui/mod.rs
pub mod accessibility;
pub mod batch_rename;
pub mod dialogs;
pub mod grid_view;
pub mod item_object;
pub mod list_view;
pub mod path_bar;
pub mod preview;
pub mod progress;
pub mod properties;
pub mod settings;
pub mod sidebar;
pub mod split_pane;
pub mod tab_menu;
pub mod theme;
pub mod trash_view;
pub mod tree_view;
pub mod window;
