use gtk::gio;
use gtk::glib;
use gtk::prelude::*;
use std::path::{Path, PathBuf};

const MAX_DIRECT_IMAGE_SIZE: u64 = 50 * 1024 * 1024;

pub fn thumbnail_path_for(path: &Path, mime: &str, size: u64) -> String {
    // First, try the freedesktop thumbnail cache.
    //
    // This lets MITOS Files reuse thumbnails already generated by
    // GNOME Files, KDE Dolphin, Thunar, etc.
    if let Some(existing) = freedesktop_thumbnail_path(path) {
        return existing.to_string_lossy().to_string();
    }

    // For small image files, show the image directly.
    if size > 0 && size <= MAX_DIRECT_IMAGE_SIZE && mime.starts_with("image/") {
        return path.to_string_lossy().to_string();
    }

    String::new()
}

fn freedesktop_thumbnail_path(path: &Path) -> Option<PathBuf> {
    let home = std::env::var_os("HOME").map(PathBuf::from)?;

    let file = gio::File::for_path(path);
    let uri = file.uri().to_string();

    let hash = glib::Checksum::checksum_string(glib::ChecksumType::MD5, &uri)?;

    let cache = home.join(".cache/thumbnails");

    for directory in ["large", "normal"] {
        let candidate = cache.join(directory).join(format!("{hash}.png"));

        if candidate.exists() {
            return Some(candidate);
        }
    }

    None
}
